/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lnc' at '8/9/17 11:33 AM' with Gradle 2.13
 *
 * @author lnc, @date 8/9/17 11:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
